<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="2" assertions="2" errors="0" warnings="0" failures="1" skipped="0" time="0.048364">
    <testsuite name="Quote" tests="2" assertions="2" errors="0" warnings="0" failures="1" skipped="0" time="0.048364">
      <testsuite name="Tests\Unit\Quote\StoreHandlerTest" file="C:\Users\Romario\Projetos\www\codeigniter4\tests\unit\Quote\StoreHandlerTest.php" tests="2" assertions="2" errors="0" warnings="0" failures="1" skipped="0" time="0.048364">
        <testcase name="testStore" class="Tests\Unit\Quote\StoreHandlerTest" classname="Tests.Unit.Quote.StoreHandlerTest" file="C:\Users\Romario\Projetos\www\codeigniter4\tests\unit\Quote\StoreHandlerTest.php" line="52" assertions="1" time="0.042246"/>
        <testcase name="testUniqueEmailStore" class="Tests\Unit\Quote\StoreHandlerTest" classname="Tests.Unit.Quote.StoreHandlerTest" file="C:\Users\Romario\Projetos\www\codeigniter4\tests\unit\Quote\StoreHandlerTest.php" line="57" assertions="1" time="0.006118">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\Quote\StoreHandlerTest::testUniqueEmailStore
Failed asserting that exception of type "RuntimeException" is thrown.</failure>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
